def Menu():
        menus = ("""
<b>/wiki [cari]</b> = Pencarian melalui wikipedia.
<b>/brainly [cari]</b> = Mencari jawaban melalui brainly.
<b>/lirik [judul]</b> = Mencari lirik lagu berdasarkan judul.
<b>/cuaca [daerah]</b> = Menampilkan cuaca di daerah berdasarkan pencarian.
<b>/sholat [daerah]</b> = Menampilkan jadwal sholat di daerah berdasarkan pencarian.
<b>/meme</b> = Random meme.
<b>/quotes</b> = Random Quotes.
<b>/artinama [nama]</b> = Menampilkan arti nama dari sesorang berdasarkan pencarian.
<b>/jodoh [pria] [wanita]</b> = Dukun cinta berdasasrkan nama pasangan.
<b>/weton [tgl] [bln] [thn]</b> = Menampilkan weton berdasarkan tanggal-bulan-tahun kelahiran.
<b>/jadian [tgl] [bln] [thn]</b> = Dukun cinta berdasarkan tanggal jadian.
<b>/quotenime</b> = Menampilan quotes dari anime secara random.
<b>/faktaunik</b> = Menampilkan faktu unik secara random.
<b>/katabijak</b> = Menampilkan kata bijak secara random.
<b>/pantun</b> = Menampilan pantun secara random.
<b>/bucin</b> = Menampilkan kata-kata bucin v1.0.
<b>/bucinn</b> = Menampilkan kata-kata bucin v2.0.
<b>/twt [link-video]</b> = Mendownload video dari twitter.
<b>/wancak</b> = Menampilkan meme dari 1cak.
<b>/bts</b> = Menampilkan foto BTS secara random.
<b>/exo</b> = Menampilkan foro EXO secara random.
<b>blackpink</b> = Menampilkan foto BLACKPINK secara random.
<b>/animefanart</b> = Menampilkan gambar anime dalam bentuk fanart.
<b>/wpanime</b> = Menampilkan wallpaper anime secara random.
<b>/wpsearch [cari]</b> = Mencari wallpaper berdasasrkan pencarian.
<b>/pinterest [cari]</b> = Mencari gambar dari pinterest berdasarkan pencarian.
<b>/phub [teks1] [teks2]</b> = Membuat logo/tulisan PORNHUB dengan teks inputan dari user.
<b>/glitch [teks1] [teks2]</b> = Membuat logo/tulisan GLITCH dengan teks inputan dari user.
<b>/avenger [teks1] [teks2]</b> = Membuat logo/tulisan AVENGER dengan teks inputan dari user.
<b>/space [teks1] [teks2]</b> = Membuat logo/tulisan SPACE dengan teks inputan dari user.
<b>/ninja [teks1] [teks2]</b> = Membuat logo/tulisan NINJA LOGO dengan teks inputan dari user.
<b>/marvel [teks1] [teks2]</b> = Membuat logo/tulisan MARVEL STUDIO dengan teks inputan dari user.
<b>/lion [teks1] [teks2]</b> = Membuat logo/tulisan LION LOGO dengan teks inputan dari user.
<b>/wolf [teks1] [teks2]</b> = Membuat logo/tulisan WOLF LOGO dengan teks inputan dari user.
<b>/steel3d [teks1] [teks2]</b> = Membuat logo/tulisan STEEL3D dengan teks inputan dari user.
        """)
        return menus